export const SERVER_URL = "https://reqres.in/";
const API_END_PREFIX = 'api/';

export const LOGIN = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
}
export const LOGOUT = {
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
}
export const REGISTER = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',
}
export const DASHBOARD = {
    DASHBOARD_DATA_REQUEST: 'DASHBOARD_DATA_REQUEST',
    DASHBOARD_DATA_SUCCESS: 'DASHBOARD_DATA_SUCCESS',
    DASHBOARD_DATA_FAILURE: 'DASHBOARD_DATA_FAILURE',
}
export const DIRECTORY = {
    LOGIN_REQUEST: 'DIRECTORY_DATA_REQUEST',
    LOGIN_SUCCESS: 'DIRECTORY_DATA_SUCCESS',
    LOGIN_FAILED: 'DIRECTORY_DATA_FAILURE',
}
export const DONATION = {
    DONATION_DATA_REQUEST: 'DONATION_DATA_REQUEST',
    DONATION_DATA_SUCCESS: 'DONATION_DATA_SUCCESS',
    DONATION_DATA_FAILURE: 'DONATION_DATA_FAILURE',
}
export const LEADERBOARD = {
    LEADERBOARD_DATA_REQUEST: 'LEADERBOARD_DATA_REQUEST',
    LEADERBOARD_DATA_SUCCESS: 'LEADERBOARD_DATA_SUCCESS',
    LEADERBOARD_DATA_FAILURE: 'LEADERBOARD_DATA_FAILURE',
}
export const TEAM = {
    TEAM_DATA_REQUEST: 'TEAM_DATA_REQUEST',
    TEAM_DATA_SUCCESS: 'TEAM_DATA_SUCCESS',
    TEAM_DATA_FAILURE: 'TEAM_DATA_FAILURE',
}
export const NOTIFICATION = {
    NOTIFICATION_DATA_REQUEST: 'NOTIFICATION_DATA_REQUEST',
    NOTIFICATION_DATA_SUCCESS: 'NOTIFICATION_DATA_SUCCESS',
    NOTIFICATION_DATA_FAILURE: 'NOTIFICATION_DATA_FAILURE',
}
export const NEWUPDATE = {
    NEWUPDATE_DATA_REQUEST: 'NEWUPDATE_DATA_REQUEST',
    NEWUPDATE_DATA_SUCCESS: 'NEWUPDATE_DATA_SUCCESS',
    NEWUPDATE_DATA_FAILURE: 'NEWUPDATE_DATA_FAILURE',
}
export const ACCOUNT = {
    ACCOUNTDETAILS_REQUEST: 'ACCOUNTDETAILS_REQUEST',
    ACCOUNTDETAILS_SUCCESS: 'ACCOUNTDETAILS_SUCCESS',
    ACCOUNTDETAILS_FAILURE: 'ACCOUNTDETAILS_FAILURE',
}
